[package]
name = "token"
version = "0.1.0"
authors = ["Jun Kimura <junkxdev@gmail.com>"]
edition = "2018"
workspace = "../../"

[dependencies]
hmcdk = { path = "../../lib" }

[lib]
crate-type = ["cdylib", "lib"]
